#cloud-config
# vim: syntax=yaml
users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKOxROwjBWRkzPhth4v6kdzvRky/cP8SXtf0iHH4+NHoa0gTinnFaV8NsOJjHNVY18TGtf8a9DdYDMsUdeIqTnn2YMqeTJUh4RqjZ3dnPgn8vxfkUzoXgNqqWjqppwXHTe7UL3WUE7vyr3TfodvR5UvCMn6Fw7THb66NJSG69dKAZd92vd6pToBgOCix3Ha+fq0PWiVpAiCtshAn+DMDFrxtSWkIPtHhmt6QrwNK33hFydSVdoaTNZWVLMailDohqsAdkIPG1TOGGgqTFrtr/bCe8kBP8EvPt2SjitgRs8kxwT/xQ4ZL7m9NbIxDRE3hkrYRWxXSdVqXbUFz7mVGJzPPLPJo/4aI8IEdUrxue2bDoIQhfDz4pSAR2GwUEzUCr3KbJqRZwjDF9jcWr4rUO+/ltXTXf5XJX0pQdrPemIb62SM773en7b2QzfMxcObWy/d+9h8QsT8SYktXFZnyyzrAkekvBVSmv5HifcW9yRPCkaKdz6ia1+QEfjhfuKkyc= appuser
write_files:
  - path: /home/yc-user/install_ruby.sh
    permissions: '0555'
    content: |
      #!/bin/bash
      sudo apt update
      sudo apt install -y ruby-full ruby-bundler build-essential
  - path: /home/yc-user/install_mongodb.sh
    permissions: '0555'
    content: |
      #!/bin/bash
      sudo apt-get update
      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
      echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
      sudo apt-get update
      sudo apt-get install -y mongodb-org
      sudo systemctl start mongod
      sudo systemctl enable mongod
  - path: /home/yc-user/deploy.sh
    permissions: '0555'
    content: |
      #!/bin/bash
      sudo apt-get update
      sudo apt-get install -y git
      cd /home/yc-user
      git clone -b monolith https://github.com/express42/reddit.git
      cd reddit && bundle install
      puma -d
runcmd:
  - bash /home/yc-user/install_ruby.sh >> /home/yc-user/deploy.log
  - bash /home/yc-user/install_mongodb.sh >> /home/yc-user/deploy.log
  - bash /home/yc-user/deploy.sh >> /home/yc-user/deploy.log
  - rm -f /home/yc-user/install_ruby.sh >> /home/yc-user/deploy.log
  - rm -f /home/yc-user/install_mongodb.sh >> /home/yc-user/deploy.log
  - rm -f /home/yc-user/deploy.sh >> /home/yc-user/deploy.log
  - rm -rf /home/yc-user/reddit >> /home/yc-user/deploy.log
